version = 1

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["react"]
  environment = [
    "nodejs",
    "browser",
    "mongo",
    "jquery",
    "cypress",
    "vitest",
    "jasmine",
    "mocha",
    "jest"
  ]